using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using Decuplr.Serialization;
using Decuplr.Serialization.Binary;
using static Decuplr.Serialization.Binary.Internal.DefaultParserEntryPoint;


namespace Decuplr.Serialization.Binary.Internal.DefaultParsers {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeDeserialize
internal  partial struct DateTimeShim{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
// This is for "TryDeserialize" constructor
internal DateTimeShim (in DateTimeShim_SJ32A9XBUFRV_TypeParserArgs parsers, ReadOnlySpan<byte> span, out int readBytes, out DeserializeResult result) :this(){
readBytes = -1;
var originalSpanLength = span.Length;
{
// Configure for argument ActualTime
var currentReadBytes = 0;
result = TryDeserialize_ActualTime (in parsers, span, out currentReadBytes, out var desResult);
ActualTime = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_ActualTime (in DateTimeShim_SJ32A9XBUFRV_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out long value){
return parsers.Parser_0_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
readBytes = originalSpanLength - span.Length;
result = DeserializeResult.Success;
}
}
}
