using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using Decuplr.Serialization;
using static Decuplr.Serialization.Binary.Internal.DefaultParserEntryPoint;


namespace Decuplr.Serialization.Binary.Internal.DefaultParsers {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeSerialize
internal  partial class LazyShim<T>{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static bool ___generated__no_invoke_LazyShim_TrySerializer (in LazyShim_XAF96RTGJHE73_TypeParserArgs<T> parsers, Decuplr.Serialization.Binary.Internal.DefaultParsers.LazyShim<T> value, Span<byte> destination, out int writtenBytes){
writtenBytes = -1;
var oglength = destination.Length;
int currentWrittenBytes;
if (!parsers.Parser_0_0.TrySerialize(value.LazyValue, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
writtenBytes = oglength - destination.Length;
return true;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_invoke_LazyShim_Serializer (in LazyShim_XAF96RTGJHE73_TypeParserArgs<T> parsers, Decuplr.Serialization.Binary.Internal.DefaultParsers.LazyShim<T> value, Span<byte> destination){
var oglength = destination.Length;
int currentWrittenBytes;
currentWrittenBytes = parsers.Parser_0_0.Serialize(value.LazyValue, destination);
destination = destination.Slice(currentWrittenBytes);
return oglength - destination.Length;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_inoke_LazyShim_GetLength(in LazyShim_XAF96RTGJHE73_TypeParserArgs<T> parsers, Decuplr.Serialization.Binary.Internal.DefaultParsers.LazyShim<T> value){
var result = 0;
result += parsers.Parser_0_0.GetBinaryLength(value.LazyValue);
return result;
}
}
}
