using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using Decuplr.Serialization;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeSerialize
public  partial struct FoamStruct{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static bool ___generated__no_invoke_FoamStruct_TrySerializer (in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.FoamStruct value, Span<byte> destination, out int writtenBytes){
writtenBytes = -1;
var oglength = destination.Length;
int currentWrittenBytes;
if (!parsers.Parser_0_0.TrySerialize(value.Data, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
if (!parsers.Parser_1_0.TrySerialize(value.Implement, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
writtenBytes = oglength - destination.Length;
return true;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_invoke_FoamStruct_Serializer (in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.FoamStruct value, Span<byte> destination){
var oglength = destination.Length;
int currentWrittenBytes;
currentWrittenBytes = parsers.Parser_0_0.Serialize(value.Data, destination);
destination = destination.Slice(currentWrittenBytes);
currentWrittenBytes = parsers.Parser_1_0.Serialize(value.Implement, destination);
destination = destination.Slice(currentWrittenBytes);
return oglength - destination.Length;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_inoke_FoamStruct_GetLength(in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.FoamStruct value){
var result = 0;
result += parsers.Parser_0_0.GetBinaryLength(value.Data);
result += parsers.Parser_1_0.GetBinaryLength(value.Implement);
return result;
}
}
}
