using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using Decuplr.Serialization;
using Decuplr.Serialization.Binary;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeDeserialize
public  partial struct FoamStruct{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
// This is for "TryDeserialize" constructor
internal FoamStruct (in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers, ReadOnlySpan<byte> span, out int readBytes, out DeserializeResult result) :this(){
readBytes = -1;
var originalSpanLength = span.Length;
{
// Configure for argument Data
var currentReadBytes = 0;
result = TryDeserialize_Data (in parsers, span, out currentReadBytes, out var desResult);
Data = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_Data (in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out int value){
return parsers.Parser_0_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
{
// Configure for argument Implement
var currentReadBytes = 0;
result = TryDeserialize_Implement (in parsers, span, out currentReadBytes, out var desResult);
Implement = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_Implement (in FoamStruct_8V1SAAV4UQJV3_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out long value){
return parsers.Parser_1_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
readBytes = originalSpanLength - span.Length;
result = DeserializeResult.Success;
}
}
}
