using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using Decuplr.Serialization;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeSerialize
public  partial class TestClass3{
public  partial class NestedClassTarget{
internal  partial class NestedClassTarget3{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static bool ___generated__no_invoke_NestedClassTarget3_TrySerializer (in NestedClassTarget3_08XCBS51PJUZ_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget.NestedClassTarget3 value, Span<byte> destination, out int writtenBytes){
writtenBytes = -1;
var oglength = destination.Length;
int currentWrittenBytes;
if (!parsers.Parser_0_0.TrySerialize(value.Safety, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
writtenBytes = oglength - destination.Length;
return true;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_invoke_NestedClassTarget3_Serializer (in NestedClassTarget3_08XCBS51PJUZ_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget.NestedClassTarget3 value, Span<byte> destination){
var oglength = destination.Length;
int currentWrittenBytes;
currentWrittenBytes = parsers.Parser_0_0.Serialize(value.Safety, destination);
destination = destination.Slice(currentWrittenBytes);
return oglength - destination.Length;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_inoke_NestedClassTarget3_GetLength(in NestedClassTarget3_08XCBS51PJUZ_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget.NestedClassTarget3 value){
var result = 0;
result += parsers.Parser_0_0.GetBinaryLength(value.Safety);
return result;
}
}
}
}
}
