using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using Decuplr.Serialization;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeSerialize
public  partial class TestClass3{
public  partial class NestedClassTarget{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static bool ___generated__no_invoke_NestedClassTarget_TrySerializer (in NestedClassTarget_7VS9HJUOT01A2_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget value, Span<byte> destination, out int writtenBytes){
writtenBytes = -1;
var oglength = destination.Length;
int currentWrittenBytes;
if (!parsers.Parser_0_0.TrySerialize(value.Target, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
if (!parsers.Parser_1_0.TrySerialize(value.Result, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
writtenBytes = oglength - destination.Length;
return true;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_invoke_NestedClassTarget_Serializer (in NestedClassTarget_7VS9HJUOT01A2_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget value, Span<byte> destination){
var oglength = destination.Length;
int currentWrittenBytes;
currentWrittenBytes = parsers.Parser_0_0.Serialize(value.Target, destination);
destination = destination.Slice(currentWrittenBytes);
currentWrittenBytes = parsers.Parser_1_0.Serialize(value.Result, destination);
destination = destination.Slice(currentWrittenBytes);
return oglength - destination.Length;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_inoke_NestedClassTarget_GetLength(in NestedClassTarget_7VS9HJUOT01A2_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3.NestedClassTarget value){
var result = 0;
result += parsers.Parser_0_0.GetBinaryLength(value.Target);
result += parsers.Parser_1_0.GetBinaryLength(value.Result);
return result;
}
}
}
}
