using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using Decuplr.Serialization;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeSerialize
public  partial class TestClass3{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static bool ___generated__no_invoke_TestClass3_TrySerializer (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3 value, Span<byte> destination, out int writtenBytes){
writtenBytes = -1;
var oglength = destination.Length;
int currentWrittenBytes;
if (!parsers.Parser_0_0.TrySerialize(value.InfoData, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
if (!parsers.Parser_1_0.TrySerialize(value.FormatData, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
if (!parsers.Parser_2_0.TrySerialize(value.ConditionGroup, destination, out currentWrittenBytes)) {
return false;
}
destination = destination.Slice(currentWrittenBytes);
writtenBytes = oglength - destination.Length;
return true;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_invoke_TestClass3_Serializer (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3 value, Span<byte> destination){
var oglength = destination.Length;
int currentWrittenBytes;
currentWrittenBytes = parsers.Parser_0_0.Serialize(value.InfoData, destination);
destination = destination.Slice(currentWrittenBytes);
currentWrittenBytes = parsers.Parser_1_0.Serialize(value.FormatData, destination);
destination = destination.Slice(currentWrittenBytes);
currentWrittenBytes = parsers.Parser_2_0.Serialize(value.ConditionGroup, destination);
destination = destination.Slice(currentWrittenBytes);
return oglength - destination.Length;
}
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
internal static int ___generated__no_inoke_TestClass3_GetLength(in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers, Decuplr.Serialization.Binary.ConsoleTests.TestClass3 value){
var result = 0;
result += parsers.Parser_0_0.GetBinaryLength(value.InfoData);
result += parsers.Parser_1_0.GetBinaryLength(value.FormatData);
result += parsers.Parser_2_0.GetBinaryLength(value.ConditionGroup);
return result;
}
}
}
