using System;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using Decuplr.Serialization;
using Decuplr.Serialization.Binary;
using static Decuplr.Serialization.Binary.Internal.AssemblyFormatProvider_Decuplr_Serialization_Binary_ConsoleTests_41QRTFMAAACQ2;


namespace Decuplr.Serialization.Binary.ConsoleTests {
// This file is automatically generated by Decuplr.Serilization.Binary library
// For more information, see https://decuplr.dev/serialization/binary

// Debug Info : Built by PartialTypeDeserialize
public  partial class TestClass3{
[GeneratedCode ("Decuplr.Serialization.Binary.SourceGenerator", "1.0.0.0")]
[EditorBrowsable(EditorBrowsableState.Never)]
// This is for "TryDeserialize" constructor
internal TestClass3 (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers, ReadOnlySpan<byte> span, out int readBytes, out DeserializeResult result) {
readBytes = -1;
var originalSpanLength = span.Length;
{
// Configure for argument InfoData
var currentReadBytes = 0;
result = TryDeserialize_InfoData (in parsers, span, out currentReadBytes, out var desResult);
InfoData = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_InfoData (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out Decuplr.Serialization.Binary.ConsoleTests.FoamStruct value){
return parsers.Parser_0_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
{
// Configure for argument FormatData
var currentReadBytes = 0;
result = TryDeserialize_FormatData (in parsers, span, out currentReadBytes, out var desResult);
FormatData = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_FormatData (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out System.Collections.Generic.List<byte> value){
return parsers.Parser_1_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
{
// Configure for argument ConditionGroup
var currentReadBytes = 0;
result = TryDeserialize_ConditionGroup (in parsers, span, out currentReadBytes, out var desResult);
ConditionGroup = desResult;
if (result != DeserializeResult.Success){
return;
}
span = span.Slice(currentReadBytes);

[MethodImpl(MethodImplOptions.AggressiveInlining)]
DeserializeResult TryDeserialize_ConditionGroup (in TestClass3_V3UCWTP448Y71_TypeParserArgs parsers,ReadOnlySpan<byte> providedSpan, out int readBytes, out (bool IsValid, bool IsCurrent, bool IsCompressed) value){
return parsers.Parser_2_0.TryDeserialize(providedSpan, out readBytes, out value);
}

}
readBytes = originalSpanLength - span.Length;
result = DeserializeResult.Success;
}
public TestClass3 () {
}
}
}
