using System;
using System.Collections.Generic;
using Decuplr.Serialization.Binary.Namespaces;

namespace Decuplr.Serialization.Binary {

    internal partial class DefaultBinaryPacker : BinaryPacker {

        private readonly ParserNamespaces Namespaces;

        public override IDefaultParserNamespace DefaultNamespace => Namespaces.Default;

        public DefaultBinaryPacker() {
            Namespaces = new ParserNamespaces(this);

            LoadDefaultParser(Namespaces);
        }

        public override IParserNamespace GetNamespace(IEnumerable<string> parserNamespace) => new ParserLocator(Namespaces, parserNamespace);

        public override IParserNamespaceSource CreateNamespace(string parserNamespace) {
            if (parserNamespace.StartsWith("Internal."))
                throw new ArgumentException("Cannot create namespaces that starts with an `Internal` prefix", nameof(parserNamespace));
            if (Namespaces.TryAddNamespace(parserNamespace, out var container))
                throw new ArgumentException("The requested namespace already exists", nameof(parserNamespace));
            return container;
        }

        // Private static members that would be generated by Source Generators itself
        static partial void LoadDefaultParser(ParserNamespaces namespaces);

    }
}
